export type { IconProps } from './Icon'
export { Icon } from './Icon'
export { TrendsIcon } from './TrendsIcon'
export { TasksIcon } from './TasksIcon'
export { TicketsIcon } from './TicketsIcon'
export { PaymentsIcon } from './PaymentsIcon'
export { ClientsIcon } from './ClientsIcon'
export { InventoryIcon } from './InventoryIcon'
export { ShopIcon } from './ShopIcon'
export { ReportsIcon } from './ReportsIcon'
export { TenderIcon } from './TenderIcon'
export { MarketingIcon } from './MarketingIcon'
export { SettingsIcon } from './SettingsIcon'
export { KnowledgeIcon } from './KnowledgeIcon'
export { CollapseIcon } from './CollapseIcon'
export { ExpandIcon } from './ExpandIcon'
export { CloseIcon } from './CloseIcon'
export { SearchIcon } from './SearchIcon'
